/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-02-17 12:04:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class left_002dmenubar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/user2/Desktop/Final%20Project/finalProject/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1578453700000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.js\"></script>\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\".../css/left-menubar.css\"> -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css\">\r\n");
      out.write("<script type=\"text/javascript\" charset=\"utf8\"\r\n");
      out.write("\tsrc=\"https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/summernote@0.8.15/dist/summernote.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/summernote@0.8.15/dist/summernote.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\theight: 1050px;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tbackground: whitesmoke;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("main .helper span {\r\n");
      out.write("\tcolor: rgba(0, 0, 0, 0.2);\r\n");
      out.write("\tfont-size: 0.4em;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu {\r\n");
      out.write("\t/* background: #5bc995; */\r\n");
      out.write("\tbackground: #88dba3;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\t/* width: 240px; */\r\n");
      out.write("\twidth: 280px;\r\n");
      out.write("\tz-index: 5;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("\tfont-family: \"Open Sans\", Helvetica Neue, Helvetica, Arial, sans-serif;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu .avatar {\r\n");
      out.write("\twidth: 280px;\r\n");
      out.write("\tbackground: rgba(0, 0, 0, 0.3);\r\n");
      out.write("\tpadding: 2em 0.5em;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin-left: -24px;\r\n");
      out.write("\tmargin-top: -24px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu .avatar img {\r\n");
      out.write("\twidth: 110px;\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tborder: 4px solid #ffea92;\r\n");
      out.write("\tbox-shadow: 0 0 0 4px rgba(255, 255, 255, 0.2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu .avatar h2 {\r\n");
      out.write("\tfont-weight: normal;\r\n");
      out.write("\tmargin-bottom: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu ul {\r\n");
      out.write("\tlist-style: none;\r\n");
      out.write("\tpadding: 0.5em 0;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu ul li {\r\n");
      out.write("\tpadding: 0.5em 1em 0.5em 3em;\r\n");
      out.write("\tfont-size: 0.95em;\r\n");
      out.write("\tfont-weight: regular;\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\tbackground-position: left 15px center;\r\n");
      out.write("\tbackground-size: auto 20px;\r\n");
      out.write("\ttransition: all 0.15s linear;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu ul li.icon-dashboard {\r\n");
      out.write("\tbackground-image: url(\"http://www.entypo.com/images//gauge.svg\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu ul li.icon-customers {\r\n");
      out.write("\tbackground-image: url(\"http://www.entypo.com/images//briefcase.svg\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu ul li.icon-users {\r\n");
      out.write("\tbackground-image: url(\"http://www.entypo.com/images//users.svg\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu ul li.icon-settings {\r\n");
      out.write("\tbackground-image: url(\"http://www.entypo.com/images//tools.svg\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu ul li:hover {\r\n");
      out.write("\tbackground-color: rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu ul li:focus {\r\n");
      out.write("\toutline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media screen and (max-width: 900px) and (min-width: 400px) {\r\n");
      out.write("\t.menu {\r\n");
      out.write("\t\twidth: 90px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu .avatar {\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t\twidth: 90px;\r\n");
      out.write("\t\tbackground: rgba(0, 0, 0, 0.3);\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu .avatar img {\r\n");
      out.write("\t\tmargin-left: -16px;\r\n");
      out.write("\t\twidth: 60px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu .avatar h2 {\r\n");
      out.write("\t\topacity: 0;\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\ttop: 50%;\r\n");
      out.write("\t\tleft: 100px;\r\n");
      out.write("\t\tmargin: 0;\r\n");
      out.write("\t\tmin-width: 200px;\r\n");
      out.write("\t\tborder-radius: 4px;\r\n");
      out.write("\t\tbackground: rgba(0, 0, 0, 0.4);\r\n");
      out.write("\t\ttransform: translate3d(-20px, -50%, 0);\r\n");
      out.write("\t\ttransition: all 0.15s ease-in-out;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu .avatar:hover h2 {\r\n");
      out.write("\t\topacity: 1;\r\n");
      out.write("\t\ttransform: translate3d(0px, -50%, 0);\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu ul li {\r\n");
      out.write("\t\theight: 60px;\r\n");
      out.write("\t\tbackground-position: center center;\r\n");
      out.write("\t\tbackground-size: 30px auto;\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu ul li span {\r\n");
      out.write("\t\topacity: 0;\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tbackground: rgba(0, 0, 0, 0.5);\r\n");
      out.write("\t\tpadding: 0.2em 0.5em;\r\n");
      out.write("\t\tborder-radius: 4px;\r\n");
      out.write("\t\ttop: 50%;\r\n");
      out.write("\t\tleft: 80px;\r\n");
      out.write("\t\ttransform: translate3d(-15px, -50%, 0);\r\n");
      out.write("\t\ttransition: all 0.15s ease-in-out;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu ul li span:before {\r\n");
      out.write("\t\tcontent: '';\r\n");
      out.write("\t\twidth: 0;\r\n");
      out.write("\t\theight: 0;\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\ttop: 50%;\r\n");
      out.write("\t\tleft: -5px;\r\n");
      out.write("\t\tborder-top: 5px solid transparent;\r\n");
      out.write("\t\tborder-bottom: 5px solid transparent;\r\n");
      out.write("\t\tborder-right: 5px solid rgba(0, 0, 0, 0.5);\r\n");
      out.write("\t\ttransform: translateY(-50%);\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu ul li:hover span {\r\n");
      out.write("\t\topacity: 1;\r\n");
      out.write("\t\ttransform: translate3d(0px, -50%, 0);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media screen and (max-width: 400px) {\r\n");
      out.write("\tbody {\r\n");
      out.write("\t\tpadding-left: 0;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu {\r\n");
      out.write("\t\twidth: 230px;\r\n");
      out.write("\t\tbox-shadow: 0 0 0 100em rgba(0, 0, 0, 0);\r\n");
      out.write("\t\ttransform: translate3d(-230px, 0, 0);\r\n");
      out.write("\t\ttransition: all 0.15s ease-in-out;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu .smartphone-menu-trigger {\r\n");
      out.write("\t\twidth: 40px;\r\n");
      out.write("\t\theight: 40px;\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tleft: 100%;\r\n");
      out.write("\t\tbackground: #5bc995;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu .smartphone-menu-trigger:before, .menu .smartphone-menu-trigger:after\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\tcontent: '';\r\n");
      out.write("\t\twidth: 50%;\r\n");
      out.write("\t\theight: 2px;\r\n");
      out.write("\t\tbackground: #fff;\r\n");
      out.write("\t\tborder-radius: 10px;\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\ttop: 45%;\r\n");
      out.write("\t\tleft: 50%;\r\n");
      out.write("\t\ttransform: translate3d(-50%, -50%, 0);\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu .smartphone-menu-trigger:after {\r\n");
      out.write("\t\ttop: 55%;\r\n");
      out.write("\t\ttransform: translate3d(-50%, -50%, 0);\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu ul li {\r\n");
      out.write("\t\tpadding: 1em 1em 1em 3em;\r\n");
      out.write("\t\tfont-size: 1.2em;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu:focus {\r\n");
      out.write("\t\ttransform: translate3d(0, 0, 0);\r\n");
      out.write("\t\tbox-shadow: 0 0 0 100em rgba(0, 0, 0, 0.6);\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu:focus .smartphone-menu-trigger {\r\n");
      out.write("\t\tpointer-events: none;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media screen and (min-width: 320px) {\r\n");
      out.write("\t.table {\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tmargin-top: 4vh;\r\n");
      out.write("\t\tmargin-left: 140px;\r\n");
      out.write("\t\twidth: 1200px;\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t\tclear: right;\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fixed_headers {\r\n");
      out.write("\tmargin-left: 390px;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tmin-width: 500px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".classify {\r\n");
      out.write("\tmargin-left: 330px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".manage a {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hide {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bold-weight {\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("        \r\n");
      out.write("textarea::placeholder {\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<nav class=\"menu\" id=\"menu\" tabindex=\"0\">\r\n");
      out.write("\t\t<div class=\"smartphone-menu-trigger\"></div>\r\n");
      out.write("\t\t<header class=\"avatar\">\r\n");
      out.write("\t\t\t<img\r\n");
      out.write("\t\t\t\tsrc=\"https://s3.amazonaws.com/uifaces/faces/twitter/kolage/128.jpg\" />\r\n");
      out.write("\t\t\t<h2>John D.</h2>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<ul class=\"manage\">\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005furl_005f8(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005furl_005f9(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t<li tabindex=\"0\" class=\"icon-users icon\"><a><span>멤버\r\n");
      out.write("\t\t\t\t\t\t관리</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"hide\">\r\n");
      out.write("\t\t\t\t\t<li class=\"homepage page1\" onclick=\"goHomepage(this, 1);\">멤버 전체</li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li tabindex=\"0\" class=\"icon-settings icon\"><a><span>문의사항</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"hide\">\r\n");
      out.write("\t\t\t\t\t<li class=\"homepage page2\" onclick=\"goHomepage(this, 2);\">전체 문의</li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li tabindex=\"0\" class=\"icon-settings icon\"><a><span>통계</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"hide\">\r\n");
      out.write("\t\t\t\t\t<li><a><span>클래스</span></a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"hide\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"homepage page3\" onclick=\"goHomepage(this, 3);\">분류별</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"homepage page4\" onclick=\"goHomepage(this, 4);\">조회수별</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"hide\">\r\n");
      out.write("\t\t\t\t\t<li><a><span>문의</span></a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"hide\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"homepage page5\" onclick=\"goHomepage(this, 5);\">분류별</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"hide\">\r\n");
      out.write("\t\t\t\t\t<li><a><span>방문기록</span></a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"hide\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"homepage page6\" onclick=\"goHomepage(this, 6);\">시간별</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"homepage page7\" onclick=\"goHomepage(this, 7);\">일자별</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"homepage page8\" onclick=\"goHomepage(this, 8);\">월별</li>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\t\t\t\r\n");
      out.write("\t\t\t\t<ul class=\"hide\">\r\n");
      out.write("\t\t\t\t\t<li><a><span>단어장</span></a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"hide\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"homepage page9\" onclick=\"goHomepage(this, 9);\">분류별</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"homepage page10\" onclick=\"goHomepage(this, 10);\">조회수별</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("            $(document).ready(function () {\r\n");
      out.write("            \tswitch(window.location.pathname) {\r\n");
      out.write("            \tcase \"/spring/inquire.ad\": \r\n");
      out.write("            \t\t$(\".page1\").css(\"font-weight\", \"bold\");\r\n");
      out.write("            \t\tbreak;\r\n");
      out.write("            \tcase \"/spring/memberManage.ad\": \r\n");
      out.write("            \t\t$(\".page2\").css(\"font-weight\", \"bold\");\r\n");
      out.write("            \t\tbreak;\r\n");
      out.write("            \tcase \"/spring/classify.cl\": \r\n");
      out.write("            \t\t$(\".page3\").css(\"font-weight\", \"bold\");\r\n");
      out.write("            \t\tbreak;\r\n");
      out.write("            \tcase \"/spring/total.cl\": \r\n");
      out.write("            \t\t$(\".page4\").css(\"font-weight\", \"bold\");\r\n");
      out.write("            \t\tbreak;\r\n");
      out.write("            \tcase \"/spring/inquire.in\": \r\n");
      out.write("            \t\t$(\".page5\").css(\"font-weight\", \"bold\");\r\n");
      out.write("            \t\tbreak;\r\n");
      out.write("            \tcase \"/spring/time.vi\": \r\n");
      out.write("            \t\t$(\".page6\").css(\"font-weight\", \"bold\");\r\n");
      out.write("            \t\tbreak;\r\n");
      out.write("            \tcase \"/spring/day.vi\": \r\n");
      out.write("            \t\t$(\".page7\").css(\"font-weight\", \"bold\");\r\n");
      out.write("            \t\tbreak;\r\n");
      out.write("            \tcase \"/spring/month.vi\": \r\n");
      out.write("            \t\t$(\".page8\").css(\"font-weight\", \"bold\");\r\n");
      out.write("            \t\tbreak;\r\n");
      out.write("            \tcase \"/spring/classify.voca\": \r\n");
      out.write("            \t\t$(\".page9\").css(\"font-weight\", \"bold\");\r\n");
      out.write("            \t\tbreak;\r\n");
      out.write("            \tcase \"/spring/total.voca\": \r\n");
      out.write("            \t\t$(\".page10\").css(\"font-weight\", \"bold\");\r\n");
      out.write("            \t\tbreak;\r\n");
      out.write("            \t\r\n");
      out.write("            \t}\r\n");
      out.write("            \t\r\n");
      out.write("                $(\".icon>a\").click(function () {\r\n");
      out.write("                    var submenu = $(this).nextAll(\"ul\");\r\n");
      out.write("                    if (submenu.is(\":visible\")) {\r\n");
      out.write("                        submenu.slideUp();\r\n");
      out.write("                    } else {\r\n");
      out.write("                        submenu.slideDown();\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                $(\".icon li>a\").click(function() {\r\n");
      out.write("                \tvar submenu = $(this).nextAll(\"ul\");\r\n");
      out.write("                \tif(submenu.is(\":visible\")) {\r\n");
      out.write("                \t\tsubmenu.slideUp();\r\n");
      out.write("                \t}else {\r\n");
      out.write("                \t\tsubmenu.slideDown();\r\n");
      out.write("                \t}\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            function goHomepage(id, value) {\r\n");
      out.write("            \tvar url = \"\";\r\n");
      out.write("            \t\r\n");
      out.write("            \tswitch(value) {\r\n");
      out.write("            \tcase 1:\r\n");
      out.write("            \t\turl = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ admin1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("            \t\tbreak;\r\n");
      out.write("            \tcase 2:\r\n");
      out.write("            \t\turl = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ admin2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("            \t\tbreak;\r\n");
      out.write("            \tcase 3:\r\n");
      out.write("            \t\turl = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ class1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("            \t\tbreak;\r\n");
      out.write("            \tcase 4:\r\n");
      out.write("            \t\turl = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ class2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("            \t\tbreak;\r\n");
      out.write("            \tcase 5:\r\n");
      out.write("            \t\turl = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ inquire }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("            \t\tbreak;\r\n");
      out.write("            \tcase 6:\r\n");
      out.write("            \t\turl = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ visit3 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("            \t\tbreak;\r\n");
      out.write("            \tcase 7:\r\n");
      out.write("            \t\turl = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ visit2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("            \t\tbreak;\r\n");
      out.write("            \tcase 8:\r\n");
      out.write("            \t\turl = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ visit3 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("            \t\tbreak;\r\n");
      out.write("            \tcase 9:\r\n");
      out.write("            \t\turl = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ voca1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("            \t\tbreak;\r\n");
      out.write("            \tcase 10:\r\n");
      out.write("            \t\turl = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ voca2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("            \t\tbreak;\r\n");
      out.write("            \t}\r\n");
      out.write("            \t\r\n");
      out.write("            \tlocation.href = url;\r\n");
      out.write("            }\r\n");
      out.write("        </script>\r\n");
      out.write("\t</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/common/left-menubar.jsp(267,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setVar("admin1");
      // /WEB-INF/views/common/left-menubar.jsp(267,3) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("memberManage.ad");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/views/common/left-menubar.jsp(268,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setVar("admin2");
      // /WEB-INF/views/common/left-menubar.jsp(268,3) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("response.ad");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/views/common/left-menubar.jsp(269,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setVar("class1");
      // /WEB-INF/views/common/left-menubar.jsp(269,3) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("classify.cl");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /WEB-INF/views/common/left-menubar.jsp(270,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setVar("class2");
      // /WEB-INF/views/common/left-menubar.jsp(270,3) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("total.cl");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /WEB-INF/views/common/left-menubar.jsp(271,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setVar("inquire");
      // /WEB-INF/views/common/left-menubar.jsp(271,3) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("inquire.in");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /WEB-INF/views/common/left-menubar.jsp(272,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setVar("visit1");
      // /WEB-INF/views/common/left-menubar.jsp(272,3) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("day.vi");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /WEB-INF/views/common/left-menubar.jsp(273,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setVar("visit2");
      // /WEB-INF/views/common/left-menubar.jsp(273,3) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("month.vi");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /WEB-INF/views/common/left-menubar.jsp(274,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setVar("visit3");
      // /WEB-INF/views/common/left-menubar.jsp(274,3) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue("time.vi");
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f8_reused = false;
    try {
      _jspx_th_c_005furl_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f8.setParent(null);
      // /WEB-INF/views/common/left-menubar.jsp(275,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f8.setVar("voca1");
      // /WEB-INF/views/common/left-menubar.jsp(275,3) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f8.setValue("classify.voca");
      int _jspx_eval_c_005furl_005f8 = _jspx_th_c_005furl_005f8.doStartTag();
      if (_jspx_th_c_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
      _jspx_th_c_005furl_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f8, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f9 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f9_reused = false;
    try {
      _jspx_th_c_005furl_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f9.setParent(null);
      // /WEB-INF/views/common/left-menubar.jsp(276,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f9.setVar("voca2");
      // /WEB-INF/views/common/left-menubar.jsp(276,3) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f9.setValue("total.voca");
      int _jspx_eval_c_005furl_005f9 = _jspx_th_c_005furl_005f9.doStartTag();
      if (_jspx_th_c_005furl_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f9);
      _jspx_th_c_005furl_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f9, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f9_reused);
    }
    return false;
  }
}
