/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-02-17 11:02:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class inquire_002dlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.4.1.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css\">\r\n");
      out.write("    <script type=\"text/javascript\" charset=\"utf8\" src=\"https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <title>외웟</title>\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        .hide {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #table_id {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #table_id_length,\r\n");
      out.write("        #table_id_info {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #table_id tbody tr {\r\n");
      out.write("        \tcursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .write {\r\n");
      out.write("        \ttransform: translateY(-40px);\r\n");
      out.write("        \tmargin-left: 20px;\r\n");
      out.write("        \tfont-size: 18px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/menubar.jsp", out, false);
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/left-menubar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"table\" style=\"display:inline-block;\">\r\n");
      out.write("        <table id=\"table_id\" class=\"display\">\r\n");
      out.write("            <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("\t\t\t\t\t<th>NO</th>              \r\n");
      out.write("                    <th>ID</th>\r\n");
      out.write("                    <th>이름</th>\r\n");
      out.write("                    <th>유형</th>\r\n");
      out.write("                    <th>문의 제목</th>\r\n");
      out.write("                    <th>등록일</th>\r\n");
      out.write("                    <th>답변여부</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("                <tr class=\"view\">\r\n");
      out.write("                \t<td>1</td>\r\n");
      out.write("                    <td>admin</td>\r\n");
      out.write("                    <td>임세웅</td>\r\n");
      out.write("                    <td>악성유저</td>\r\n");
      out.write("                    <td>악성유저 신승환 신고합니다</td>\r\n");
      out.write("                    <td>2020-02-11</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <select>\r\n");
      out.write("                            <option value=\"Y\" selected>Y</option>\r\n");
      out.write("                            <option value=\"N\">N</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr class=\"inquire\">\r\n");
      out.write("                \t<td colspan=\"7\">\r\n");
      out.write("                \t\t<textarea style=\"width:100%; height:200px\" placeholder=\"이 유저는 정말 안되겠습니다. 당장 처리하지 않으면 전 접겠습니다.\" readonly></textarea>\r\n");
      out.write("                \t</td>\r\n");
      out.write("                \t<td style=\"display:none;\"></td>\r\n");
      out.write("                \t<td style=\"display:none;\"></td>\r\n");
      out.write("                \t<td style=\"display:none;\"></td>\r\n");
      out.write("                \t<td style=\"display:none;\"></td>\r\n");
      out.write("                \t<td style=\"display:none;\"></td>\r\n");
      out.write("                \t<td style=\"display:none;\"></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr class=\"answer\">\r\n");
      out.write("                \t<td colspan=\"7\">\r\n");
      out.write("                \t\t<textarea style=\"width:100%; height:200px\" placeholder=\"아직 답변이 작성되지 않았습니다.\" readonly></textarea>\r\n");
      out.write("                \t</td>\r\n");
      out.write("                \t<td style=\"display:none;\"></td>\r\n");
      out.write("                \t<td style=\"display:none;\"></td>\r\n");
      out.write("                \t<td style=\"display:none;\"></td>\r\n");
      out.write("                \t<td style=\"display:none;\"></td>\r\n");
      out.write("                \t<td style=\"display:none;\"></td>\r\n");
      out.write("                \t<td style=\"display:none;\"></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr class=\"view\">\r\n");
      out.write("                \t<td>2</td>\r\n");
      out.write("                    <td>hwan</td>\r\n");
      out.write("                    <td>신승환</td>\r\n");
      out.write("                    <td>시스템</td>\r\n");
      out.write("                    <td>에바네요</td>\r\n");
      out.write("                    <td>2019-08-31</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <select>\r\n");
      out.write("                            <option value=\"Y\" selected>Y</option>\r\n");
      out.write("                            <option value=\"N\">N</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr class=\"view\">\r\n");
      out.write("                \t<td>3</td>\r\n");
      out.write("                    <td>hyuk</td>\r\n");
      out.write("                    <td>이진혁</td>\r\n");
      out.write("                    <td>계정</td>\r\n");
      out.write("                    <td>잘 지내십니까</td>\r\n");
      out.write("                    <td>2019-08-31</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <select>\r\n");
      out.write("                            <option value=\"Y\" selected>Y</option>\r\n");
      out.write("                            <option value=\"N\">N</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr class=\"view\">\r\n");
      out.write("                \t<td>4</td>\r\n");
      out.write("                    <td>chan</td>\r\n");
      out.write("                    <td>이재찬</td>\r\n");
      out.write("                    <td>악성유저</td>\r\n");
      out.write("                    <td>진짜 못참겠네요</td>\r\n");
      out.write("                    <td>2019-08-31</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <select>\r\n");
      out.write("                            <option value=\"Y\" selected>Y</option>\r\n");
      out.write("                            <option value=\"N\">N</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr class=\"view\">\r\n");
      out.write("                \t<td>5</td>\r\n");
      out.write("                    <td>anonymous</td>\r\n");
      out.write("                    <td>누군가</td>\r\n");
      out.write("                    <td>계정</td>\r\n");
      out.write("                    <td>난 어나니머스다</td>\r\n");
      out.write("                    <td>2019-08-31</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <select>\r\n");
      out.write("                            <option value=\"Y\" selected>Y</option>\r\n");
      out.write("                            <option value=\"N\">N</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr class=\"view\">\r\n");
      out.write("                \t<td>5.5</td>\r\n");
      out.write("                    <td>admin</td>\r\n");
      out.write("                    <td>임세웅</td>\r\n");
      out.write("                    <td>악성유저</td>\r\n");
      out.write("                    <td>악성유저 신승환 신고합니다</td>\r\n");
      out.write("                    <td>2020-02-11</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <select>\r\n");
      out.write("                            <option value=\"Y\" selected>Y</option>\r\n");
      out.write("                            <option value=\"N\">N</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr class=\"view\">\r\n");
      out.write("                \t<td>6</td>\r\n");
      out.write("                    <td>hwan</td>\r\n");
      out.write("                    <td>신승환</td>\r\n");
      out.write("                    <td>시스템</td>\r\n");
      out.write("                    <td>에바네요</td>\r\n");
      out.write("                    <td>2019-08-31</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <select>\r\n");
      out.write("                            <option value=\"Y\" selected>Y</option>\r\n");
      out.write("                            <option value=\"N\">N</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr class=\"view\">\r\n");
      out.write("                \t<td>7</td>\r\n");
      out.write("                    <td>hyuk</td>\r\n");
      out.write("                    <td>이진혁</td>\r\n");
      out.write("                    <td>계정</td>\r\n");
      out.write("                    <td>잘 지내십니까</td>\r\n");
      out.write("                    <td>2019-08-31</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <select>\r\n");
      out.write("                            <option value=\"Y\" selected>Y</option>\r\n");
      out.write("                            <option value=\"N\">N</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr class=\"view\">\r\n");
      out.write("                \t<td>8</td>\r\n");
      out.write("                    <td>chan</td>\r\n");
      out.write("                    <td>이재찬</td>\r\n");
      out.write("                    <td>악성유저</td>\r\n");
      out.write("                    <td>진짜 못참겠네요</td>\r\n");
      out.write("                    <td>2019-08-31</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <select>\r\n");
      out.write("                            <option value=\"Y\" selected>Y</option>\r\n");
      out.write("                            <option value=\"N\">N</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr class=\"view\">\r\n");
      out.write("                \t<td>9</td>\r\n");
      out.write("                    <td>anonymous</td>\r\n");
      out.write("                    <td>누군가</td>\r\n");
      out.write("                    <td>계정</td>\r\n");
      out.write("                    <td>난 어나니머스다</td>\r\n");
      out.write("                    <td>2019-08-31</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <select>\r\n");
      out.write("                            <option value=\"Y\" selected>Y</option>\r\n");
      out.write("                            <option value=\"N\">N</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr class=\"view\">\r\n");
      out.write("                \t<td>10</td>\r\n");
      out.write("                    <td>admin</td>\r\n");
      out.write("                    <td>임세웅</td>\r\n");
      out.write("                    <td>악성유저</td>\r\n");
      out.write("                    <td>악성유저 신승환 신고합니다</td>\r\n");
      out.write("                    <td>2020-02-11</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <select>\r\n");
      out.write("                            <option value=\"Y\" selected>Y</option>\r\n");
      out.write("                            <option value=\"N\">N</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr class=\"view\">\r\n");
      out.write("                \t<td>11</td>\r\n");
      out.write("                    <td>hwan</td>\r\n");
      out.write("                    <td>신승환</td>\r\n");
      out.write("                    <td>시스템</td>\r\n");
      out.write("                    <td>에바네요</td>\r\n");
      out.write("                    <td>2019-08-31</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <select>\r\n");
      out.write("                            <option value=\"Y\" selected>Y</option>\r\n");
      out.write("                            <option value=\"N\">N</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr class=\"view\">\r\n");
      out.write("                \t<td>11.5</td>\r\n");
      out.write("                    <td>hyuk</td>\r\n");
      out.write("                    <td>이진혁</td>\r\n");
      out.write("                    <td>계정</td>\r\n");
      out.write("                    <td>잘 지내십니까</td>\r\n");
      out.write("                    <td>2019-08-31</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <select>\r\n");
      out.write("                            <option value=\"Y\" selected>Y</option>\r\n");
      out.write("                            <option value=\"N\">N</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr class=\"view\">\r\n");
      out.write("                \t<td>12</td>\r\n");
      out.write("                    <td>chan</td>\r\n");
      out.write("                    <td>이재찬</td>\r\n");
      out.write("                    <td>악성유저</td>\r\n");
      out.write("                    <td>진짜 못참겠네요</td>\r\n");
      out.write("                    <td>2019-08-31</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <select>\r\n");
      out.write("                            <option value=\"Y\" selected>Y</option>\r\n");
      out.write("                            <option value=\"N\">N</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr class=\"view\">\r\n");
      out.write("                \t<td>13</td>\r\n");
      out.write("                    <td>anonymous</td>\r\n");
      out.write("                    <td>누군가</td>\r\n");
      out.write("                    <td>계정</td>\r\n");
      out.write("                    <td>난 어나니머스다</td>\r\n");
      out.write("                    <td>2019-08-31</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <select>\r\n");
      out.write("                            <option value=\"Y\" selected>Y</option>\r\n");
      out.write("                            <option value=\"N\">N</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("        <button class=\"write\">글쓰기</button>\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            $(document).ready(function () {\r\n");
      out.write("                var table = $('#table_id').DataTable({\r\n");
      out.write("                \t\"ordering\":false\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                $(\".inquire\").hide();\r\n");
      out.write("                $(\".answer\").hide();\r\n");
      out.write("                \r\n");
      out.write("\t            //content 클래스를 가진 div를 표시/숨김(토글)\r\n");
      out.write("\t            $(\".view\").click(function() {\r\n");
      out.write("\t             \t$(this).next(\".inquire\").slideToggle();\r\n");
      out.write("\t             \t$(this).next(\".inquire\").next(\".answer\").slideToggle();\r\n");
      out.write("\t            });\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
