/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-02-14 09:00:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/user2/Desktop/Final%20Project/finalProject/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1578453700000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>SEW</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        /* 전체 틀 */\r\n");
      out.write("        html, body {\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .tab, #tab0, #tab1, #tab2, #tab3, #tab4 {\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            box-shadow: 6px 0px 6px rgba(0, 0, 0, 0.3);\r\n");
      out.write("            transition: all 0.5s ease;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        .tab:hover ~ div, #tab0:hover ~ div, #tab1:hover ~ div, #tab2:hover ~ div, #tab3:hover ~ div, #tab4:hover ~ div {\r\n");
      out.write("            transform: translateX(-80vw);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #tab3:hover .wra3 {\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #tab2:hover .wra2 {\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #tab1:hover .wra1 {\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #tab0:hover .wra0 {\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #tab0 {\r\n");
      out.write("            width: 100vw;\r\n");
      out.write("            background: black;\r\n");
      out.write("        }\r\n");
      out.write("        #tab1 {\r\n");
      out.write("            width: 95vw;\r\n");
      out.write("            background: #31152b;\r\n");
      out.write("        }\r\n");
      out.write("        #tab1::after {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            width: 5vw;\r\n");
      out.write("            height: 25vh;\r\n");
      out.write("            background: #31152b;\r\n");
      out.write("            /* background: rgba(0,0,0,0.6); */\r\n");
      out.write("            border-radius: 0 20px 20px 0;\r\n");
      out.write("            top: 75%;\r\n");
      out.write("            right: -5vw;\r\n");
      out.write("        }\r\n");
      out.write("        #tab2 {\r\n");
      out.write("            width: 90vw;\r\n");
      out.write("            background: #723147;\r\n");
      out.write("        }\r\n");
      out.write("        #tab2::after {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            width: 5vw;\r\n");
      out.write("            height: 25vh;\r\n");
      out.write("            background: #723147;\r\n");
      out.write("            border-radius: 0 20px 20px 0;\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            right: -5vw;\r\n");
      out.write("        }\r\n");
      out.write("        #tab3 {\r\n");
      out.write("            width: 85vw;\r\n");
      out.write("            background: #cc4452;\r\n");
      out.write("        }\r\n");
      out.write("        #tab3::after {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            width: 5vw;\r\n");
      out.write("            height: 25vh;\r\n");
      out.write("            background: #cc4452;\r\n");
      out.write("            border-radius: 0 20px 20px 0;\r\n");
      out.write("            top: 25%;\r\n");
      out.write("            right: -5vw;\r\n");
      out.write("        }\r\n");
      out.write("        #tab4 {\r\n");
      out.write("            width: 80vw;\r\n");
      out.write("            /* background: #e6b098; */\r\n");
      out.write("            background: #8A4B08;\r\n");
      out.write("        }\r\n");
      out.write("        #tab4::after {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            width: 5vw;\r\n");
      out.write("            height: 25vh;\r\n");
      out.write("            /* background: #e6b098; */\r\n");
      out.write("            background: lightgray;\r\n");
      out.write("            border-radius: 0 20px 20px 0;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            right: -5vw;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .wrapper {\r\n");
      out.write("            /* height: 100%; \r\n");
      out.write("            width: 100%;  */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .message {\r\n");
      out.write("            -webkit-box-sizing: border-box;\r\n");
      out.write("            -moz-box-sizing: border-box;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            width: 100%; \r\n");
      out.write("            height:25%;\r\n");
      out.write("            bottom: 0; \r\n");
      out.write("            display: block;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            background-color: rgba(0,0,0,0.6);\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            padding: 0.5em;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .wra3, .wra2, .wra1, .wra0 {\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* tab0 */\r\n");
      out.write("        @import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300);\r\n");
      out.write("        #tab0 {\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        font-weight: 300;\r\n");
      out.write("        }\r\n");
      out.write("        #tab0 {\r\n");
      out.write("        font-family: 'Source Sans Pro', sans-serif;\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-weight: 300;\r\n");
      out.write("        }\r\n");
      out.write("        #tab0 ::-webkit-input-placeholder {\r\n");
      out.write("        /* WebKit browsers */\r\n");
      out.write("\r\n");
      out.write("        font-family: 'Source Sans Pro', sans-serif;\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-weight: 300;\r\n");
      out.write("        }\r\n");
      out.write("        #tab0 :-moz-placeholder {\r\n");
      out.write("        /* Mozilla Firefox 4 to 18 */\r\n");
      out.write("\r\n");
      out.write("        font-family: 'Source Sans Pro', sans-serif;\r\n");
      out.write("        color: white;\r\n");
      out.write("        opacity: 1;\r\n");
      out.write("        font-weight: 300;\r\n");
      out.write("        }\r\n");
      out.write("        #tab0 ::-moz-placeholder {\r\n");
      out.write("        /* Mozilla Firefox 19+ */\r\n");
      out.write("\r\n");
      out.write("        font-family: 'Source Sans Pro', sans-serif;\r\n");
      out.write("        color: white;\r\n");
      out.write("        opacity: 1;\r\n");
      out.write("        font-weight: 300;\r\n");
      out.write("        }\r\n");
      out.write("        #tab0 :-ms-input-placeholder {\r\n");
      out.write("        /* Internet Explorer 10+ */\r\n");
      out.write("\r\n");
      out.write("        font-family: 'Source Sans Pro', sans-serif;\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-weight: 300;\r\n");
      out.write("        }\r\n");
      out.write("        #tab0 .wrapper {\r\n");
      out.write("        background: #50a3a2;\r\n");
      out.write("        background: -webkit-linear-gradient(top left, #50a3a2 0%, #53e3a6 100%);\r\n");
      out.write("        background: -moz-linear-gradient(top left, #50a3a2 0%, #53e3a6 100%);\r\n");
      out.write("        background: -o-linear-gradient(top left, #50a3a2 0%, #53e3a6 100%);\r\n");
      out.write("        background: linear-gradient(to bottom right, #50a3a2 0%, #53e3a6 100%);\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 50%;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 400px;\r\n");
      out.write("        margin-top: -200px;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("        #tab0 .wrapper.form-success .container h1 {\r\n");
      out.write("        transform: translateY(85px);\r\n");
      out.write("        }\r\n");
      out.write("        #tab0 .container {\r\n");
      out.write("        max-width: 600px;\r\n");
      out.write("        margin: 0 auto;\r\n");
      out.write("        padding: 80px 0;\r\n");
      out.write("        height: 400px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        #tab0 .container h1 {\r\n");
      out.write("        font-size: 40px;\r\n");
      out.write("        transition-duration: 1s;\r\n");
      out.write("        transition-timing-function: ease-in-put;\r\n");
      out.write("        font-weight: 200;\r\n");
      out.write("        }\r\n");
      out.write("        #tab0 form {\r\n");
      out.write("        padding: 20px 0;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        z-index: 2;\r\n");
      out.write("        }\r\n");
      out.write("        #tab0 form input {\r\n");
      out.write("        appearance: none;\r\n");
      out.write("        outline: 0;\r\n");
      out.write("        border: 1px solid rgba(255, 255, 255, 0.4);\r\n");
      out.write("        background-color: rgba(255, 255, 255, 0.2);\r\n");
      out.write("        width: 250px;\r\n");
      out.write("        border-radius: 3px;\r\n");
      out.write("        padding: 10px 15px;\r\n");
      out.write("        margin: 0 auto 10px auto;\r\n");
      out.write("        display: block;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("        color: white;\r\n");
      out.write("        transition-duration: 0.25s;\r\n");
      out.write("        font-weight: 300;\r\n");
      out.write("        }\r\n");
      out.write("        #tab0 form input:hover {\r\n");
      out.write("        background-color: rgba(255, 255, 255, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("        #tab0 form input:focus {\r\n");
      out.write("        background-color: white;\r\n");
      out.write("        width: 300px;\r\n");
      out.write("        color: #53e3a6;\r\n");
      out.write("        }\r\n");
      out.write("        #tab0 form button {\r\n");
      out.write("        appearance: none;\r\n");
      out.write("        outline: 0;\r\n");
      out.write("        background-color: white;\r\n");
      out.write("        border: 0;\r\n");
      out.write("        padding: 10px 15px;\r\n");
      out.write("        color: #53e3a6;\r\n");
      out.write("        border-radius: 3px;\r\n");
      out.write("        width: 250px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("        transition-duration: 0.25s;\r\n");
      out.write("        }\r\n");
      out.write("        #tab0 form button:hover {\r\n");
      out.write("        background-color: #f5f7f9;\r\n");
      out.write("        }\r\n");
      out.write("        #tab0 .bg-bubbles {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        z-index: 1;\r\n");
      out.write("        }\r\n");
      out.write("        .bg-bubbles li {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        list-style: none;\r\n");
      out.write("        display: block;\r\n");
      out.write("        width: 40px;\r\n");
      out.write("        height: 40px;\r\n");
      out.write("        background-color: rgba(255, 255, 255, 0.15);\r\n");
      out.write("        bottom: -160px;\r\n");
      out.write("        -webkit-animation: square 25s infinite;\r\n");
      out.write("        animation: square 25s infinite;\r\n");
      out.write("        -webkit-transition-timing-function: linear;\r\n");
      out.write("        transition-timing-function: linear;\r\n");
      out.write("        }\r\n");
      out.write("        .bg-bubbles li:nth-child(1) {\r\n");
      out.write("        left: 10%;\r\n");
      out.write("        }\r\n");
      out.write("        .bg-bubbles li:nth-child(2) {\r\n");
      out.write("        left: 20%;\r\n");
      out.write("        width: 80px;\r\n");
      out.write("        height: 80px;\r\n");
      out.write("        animation-delay: 2s;\r\n");
      out.write("        animation-duration: 17s;\r\n");
      out.write("        }\r\n");
      out.write("        .bg-bubbles li:nth-child(3) {\r\n");
      out.write("        left: 25%;\r\n");
      out.write("        animation-delay: 4s;\r\n");
      out.write("        }\r\n");
      out.write("        .bg-bubbles li:nth-child(4) {\r\n");
      out.write("        left: 40%;\r\n");
      out.write("        width: 60px;\r\n");
      out.write("        height: 60px;\r\n");
      out.write("        animation-duration: 22s;\r\n");
      out.write("        background-color: rgba(255, 255, 255, 0.25);\r\n");
      out.write("        }\r\n");
      out.write("        .bg-bubbles li:nth-child(5) {\r\n");
      out.write("        left: 70%;\r\n");
      out.write("        }\r\n");
      out.write("        .bg-bubbles li:nth-child(6) {\r\n");
      out.write("        left: 80%;\r\n");
      out.write("        width: 120px;\r\n");
      out.write("        height: 120px;\r\n");
      out.write("        animation-delay: 3s;\r\n");
      out.write("        background-color: rgba(255, 255, 255, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("        .bg-bubbles li:nth-child(7) {\r\n");
      out.write("        left: 32%;\r\n");
      out.write("        width: 160px;\r\n");
      out.write("        height: 160px;\r\n");
      out.write("        animation-delay: 7s;\r\n");
      out.write("        }\r\n");
      out.write("        .bg-bubbles li:nth-child(8) {\r\n");
      out.write("        left: 55%;\r\n");
      out.write("        width: 20px;\r\n");
      out.write("        height: 20px;\r\n");
      out.write("        animation-delay: 15s;\r\n");
      out.write("        animation-duration: 40s;\r\n");
      out.write("        }\r\n");
      out.write("        .bg-bubbles li:nth-child(9) {\r\n");
      out.write("        left: 25%;\r\n");
      out.write("        width: 10px;\r\n");
      out.write("        height: 10px;\r\n");
      out.write("        animation-delay: 2s;\r\n");
      out.write("        animation-duration: 40s;\r\n");
      out.write("        background-color: rgba(255, 255, 255, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("        .bg-bubbles li:nth-child(10) {\r\n");
      out.write("        left: 90%;\r\n");
      out.write("        width: 160px;\r\n");
      out.write("        height: 160px;\r\n");
      out.write("        animation-delay: 11s;\r\n");
      out.write("        }\r\n");
      out.write("        @-webkit-keyframes square {\r\n");
      out.write("        0% {\r\n");
      out.write("            transform: translateY(0);\r\n");
      out.write("        }\r\n");
      out.write("        100% {\r\n");
      out.write("            transform: translateY(-700px) rotate(600deg);\r\n");
      out.write("        }\r\n");
      out.write("        }\r\n");
      out.write("        @keyframes square {\r\n");
      out.write("        0% {\r\n");
      out.write("            transform: translateY(0);\r\n");
      out.write("        }\r\n");
      out.write("        100% {\r\n");
      out.write("            transform: translateY(-700px) rotate(600deg);\r\n");
      out.write("        }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* tab image, h1 */\r\n");
      out.write("        .img-base {\r\n");
      out.write("            background-position: center center;\r\n");
      out.write("            background-repeat:  no-repeat;\r\n");
      out.write("            background-attachment: fixed;\r\n");
      out.write("            background-size:  cover;\r\n");
      out.write("            background-color: #999;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .h1-base {\r\n");
      out.write("            /* margin-left: 11vw; */\r\n");
      out.write("            font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            font-size: 40px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .font {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 70vh;\r\n");
      out.write("            left: 50%;\r\n");
      out.write("            transform: translate(-50%, -50%);\r\n");
      out.write("            background: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* tab1 */\r\n");
      out.write("        .tab1-img {\r\n");
      out.write("            width: 35vw;\r\n");
      out.write("            height: 60vh;\r\n");
      out.write("            margin-top: 7vh;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* tab3 */\r\n");
      out.write("        .tab1-img1 {\r\n");
      out.write("            width: 35vw;\r\n");
      out.write("            height: 60vh;\r\n");
      out.write("            margin-top: 7vh;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* tab2 */\r\n");
      out.write("        .tab2-img {\r\n");
      out.write("            width: 35vw;\r\n");
      out.write("            height: 60vh;\r\n");
      out.write("            margin-top: 7vh;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* tab3 */\r\n");
      out.write("        .tab3-img1 {\r\n");
      out.write("            width: 35vw;\r\n");
      out.write("            height: 60vh;\r\n");
      out.write("            margin-top: 7vh;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tab3-img2 {\r\n");
      out.write("            width: 35vw;\r\n");
      out.write("            height: 60vh;\r\n");
      out.write("            margin-top: 7vh;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* tab4 */\r\n");
      out.write("        #tab4 { \r\n");
      out.write("            background-image: url(resources/images/메인.jpg) ;\r\n");
      out.write("            background-position: center center;\r\n");
      out.write("            background-repeat:  no-repeat;\r\n");
      out.write("            background-attachment: fixed;\r\n");
      out.write("            background-size:  cover;\r\n");
      out.write("            background-color: #999;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #tab4{\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            font-family: exo, sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"tab0\">\r\n");
      out.write("        <div class=\"wrapper wra0\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <h1>Welcome</h1>\r\n");
      out.write("    \r\n");
      out.write("                <form class=\"form\">\r\n");
      out.write("                    <input type=\"text\" placeholder=\"Username\">\r\n");
      out.write("                    <input type=\"password\" placeholder=\"Password\">\r\n");
      out.write("                    <button type=\"submit\" id=\"login-button\">Login</button>\r\n");
      out.write("                    <p><a href=\"\" onclick=\"\">다음에 할게요</a></p>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <script>\r\n");
      out.write("            $(\"#login-button\").click(function (event) {\r\n");
      out.write("                event.preventDefault();\r\n");
      out.write("\r\n");
      out.write("                $('form').fadeOut(500);\r\n");
      out.write("                $('.wrapper').addClass('form-success');\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"tab1\">\r\n");
      out.write("        <img src=\"img/3.PNG\" class=\"img-base tab1-img\">\r\n");
      out.write("        <div class=\"wrapper wra1\">\r\n");
      out.write("            <div class=\"message msg1\">\r\n");
      out.write("                <h1>온라인으로 나만의 단어장과 함께 공부할 친구를 찾으세요!</h1>    \r\n");
      out.write("                <p>저희 '외웟' 홈페이지에서는 자신의 단어장을 만들고, 그로 인해 재밌는 게임으로 공부를 할 수 있으며, 클래스를 꾸려 함께 공부할 수 있게 해놓았습니다.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"tab2\">\r\n");
      out.write("        <img src=\"img/2-2.PNG\" class=\"img-base tab2-img\">\r\n");
      out.write("        <div class=\"wrapper wra2\">\r\n");
      out.write("            <div class=\"message\">\r\n");
      out.write("                <h1>온라인으로 나만의 단어장과 함께 공부할 친구를 찾으세요!</h1>    \r\n");
      out.write("                <p>저희 '외웟' 홈페이지에서는 자신의 단어장을 만들고, 그로 인해 재밌는 게임으로 공부를 할 수 있으며, 클래스를 꾸려 함께 공부할 수 있게 해놓았습니다.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"tab3\">\r\n");
      out.write("        <img src=\"img/1.PNG\" alt=\"\" class=\"img-base tab3-img1\">\r\n");
      out.write("        <img src=\"img/2-1.PNG\" class=\"img-base tab3-img2\">\r\n");
      out.write("        <div class=\"wrapper wra3\">\r\n");
      out.write("            <div class=\"message\">\r\n");
      out.write("                <h1>온라인으로 나만의 단어장과 함께 공부할 친구를 찾으세요!</h1>    \r\n");
      out.write("                <p>저희 '외웟' 홈페이지에서는 자신의 단어장을 만들고, 그로 인해 재밌는 게임으로 공부를 할 수 있으며, 클래스를 꾸려 함께 공부할 수 있게 해놓았습니다.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"tab4\">\r\n");
      out.write("        <!-- <img src=\"img/1대1.jpg\" class=\"img-base\">\r\n");
      out.write("        <div class=\"font\">\r\n");
      out.write("        <h1 class=\"h1-base\">온라인으로 단어를 함께 공부해 나가는 선생님을 만나보세요!</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <p></p> -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"wrapper wra4\">\r\n");
      out.write("       \t\t");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t<button onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ admin1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\">inquire.ad</button>\r\n");
      out.write("        \r\n");
      out.write("            <div class=\"message\">\r\n");
      out.write("                <h1>온라인으로 나만의 단어장과 함께 공부할 친구를 찾으세요!</h1>    \r\n");
      out.write("                <p>저희 '외웟' 홈페이지에서는 자신의 단어장을 만들고, 그로 인해 재밌는 게임으로 공부를 할 수 있으며, 클래스를 꾸려 함께 공부할 수 있게 해놓았습니다.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /index.jsp(483,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setVar("admin1");
      // /index.jsp(483,9) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("inquire.ad");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
