/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-02-17 06:55:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/user2/Desktop/Final%20Project/finalProject/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1578453700000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("    <title>SEW</title>\n");
      out.write("    <style>\n");
      out.write("        /* 전체 틀 */\n");
      out.write("        html, body {\n");
      out.write("            height: 100%;\n");
      out.write("            margin: 0;\n");
      out.write("        }\n");
      out.write("        .tab, #tab0, #tab1, #tab2, #tab3, #tab4 {\n");
      out.write("            height: 100%;\n");
      out.write("            position: absolute;\n");
      out.write("            box-shadow: 6px 0px 6px rgba(0, 0, 0, 0.3);\n");
      out.write("            transition: all 0.5s ease;\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("        .tab:hover ~ div, #tab0:hover ~ div, #tab1:hover ~ div, #tab2:hover ~ div, #tab3:hover ~ div, #tab4:hover ~ div {\n");
      out.write("            transform: translateX(-80vw);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        #tab3:hover .wra3 {\n");
      out.write("            opacity: 1;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        #tab2:hover .wra2 {\n");
      out.write("            opacity: 1;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        #tab1:hover .wra1 {\n");
      out.write("            opacity: 1;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        #tab0:hover .wra0 {\n");
      out.write("            opacity: 1;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        #tab0 {\n");
      out.write("            width: 100vw;\n");
      out.write("            background: black;\n");
      out.write("        }\n");
      out.write("        #tab1 {\n");
      out.write("            width: 95vw;\n");
      out.write("            background: #31152b;\n");
      out.write("        }\n");
      out.write("        #tab1::after {\n");
      out.write("            content: '';\n");
      out.write("            position: absolute;\n");
      out.write("            width: 5vw;\n");
      out.write("            height: 25vh;\n");
      out.write("            background: #31152b;\n");
      out.write("            /* background: rgba(0,0,0,0.6); */\n");
      out.write("            border-radius: 0 20px 20px 0;\n");
      out.write("            top: 75%;\n");
      out.write("            right: -5vw;\n");
      out.write("        }\n");
      out.write("        #tab2 {\n");
      out.write("            width: 90vw;\n");
      out.write("            background: #723147;\n");
      out.write("        }\n");
      out.write("        #tab2::after {\n");
      out.write("            content: '';\n");
      out.write("            position: absolute;\n");
      out.write("            width: 5vw;\n");
      out.write("            height: 25vh;\n");
      out.write("            background: #723147;\n");
      out.write("            border-radius: 0 20px 20px 0;\n");
      out.write("            top: 50%;\n");
      out.write("            right: -5vw;\n");
      out.write("        }\n");
      out.write("        #tab3 {\n");
      out.write("            width: 85vw;\n");
      out.write("            background: #cc4452;\n");
      out.write("        }\n");
      out.write("        #tab3::after {\n");
      out.write("            content: '';\n");
      out.write("            position: absolute;\n");
      out.write("            width: 5vw;\n");
      out.write("            height: 25vh;\n");
      out.write("            background: #cc4452;\n");
      out.write("            border-radius: 0 20px 20px 0;\n");
      out.write("            top: 25%;\n");
      out.write("            right: -5vw;\n");
      out.write("        }\n");
      out.write("        #tab4 {\n");
      out.write("            width: 80vw;\n");
      out.write("            background: #e6b098;\n");
      out.write("        }\n");
      out.write("        #tab4::after {\n");
      out.write("            content: '';\n");
      out.write("            position: absolute;\n");
      out.write("            width: 5vw;\n");
      out.write("            height: 25vh;\n");
      out.write("            /* background: #e6b098; */\n");
      out.write("            background: whitesmoke;\n");
      out.write("            border-radius: 0 20px 20px 0;\n");
      out.write("            top: 0;\n");
      out.write("            right: -5vw;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .wrapper {\n");
      out.write("            /* height: 100%; \n");
      out.write("            width: 100%;  */\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .message {\n");
      out.write("            -webkit-box-sizing: border-box;\n");
      out.write("            -moz-box-sizing: border-box;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("            width: 100%; \n");
      out.write("            height:25%;\n");
      out.write("            bottom: 0; \n");
      out.write("            display: block;\n");
      out.write("            position: absolute;\n");
      out.write("            background-color: rgba(0,0,0,0.6);\n");
      out.write("            color: #fff;\n");
      out.write("            padding: 0.5em;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .wra3, .wra2, .wra1, .wra0 {\n");
      out.write("            opacity: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* tab0 */\n");
      out.write("        @import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300);\n");
      out.write("        #tab0 {\n");
      out.write("        box-sizing: border-box;\n");
      out.write("        margin: 0;\n");
      out.write("        padding: 0;\n");
      out.write("        font-weight: 300;\n");
      out.write("        }\n");
      out.write("        #tab0 {\n");
      out.write("        font-family: 'Source Sans Pro', sans-serif;\n");
      out.write("        color: white;\n");
      out.write("        font-weight: 300;\n");
      out.write("        }\n");
      out.write("        #tab0 ::-webkit-input-placeholder {\n");
      out.write("        /* WebKit browsers */\n");
      out.write("\n");
      out.write("        font-family: 'Source Sans Pro', sans-serif;\n");
      out.write("        color: white;\n");
      out.write("        font-weight: 300;\n");
      out.write("        }\n");
      out.write("        #tab0 :-moz-placeholder {\n");
      out.write("        /* Mozilla Firefox 4 to 18 */\n");
      out.write("\n");
      out.write("        font-family: 'Source Sans Pro', sans-serif;\n");
      out.write("        color: white;\n");
      out.write("        opacity: 1;\n");
      out.write("        font-weight: 300;\n");
      out.write("        }\n");
      out.write("        #tab0 ::-moz-placeholder {\n");
      out.write("        /* Mozilla Firefox 19+ */\n");
      out.write("\n");
      out.write("        font-family: 'Source Sans Pro', sans-serif;\n");
      out.write("        color: white;\n");
      out.write("        opacity: 1;\n");
      out.write("        font-weight: 300;\n");
      out.write("        }\n");
      out.write("        #tab0 :-ms-input-placeholder {\n");
      out.write("        /* Internet Explorer 10+ */\n");
      out.write("\n");
      out.write("        font-family: 'Source Sans Pro', sans-serif;\n");
      out.write("        color: white;\n");
      out.write("        font-weight: 300;\n");
      out.write("        }\n");
      out.write("        #tab0 .wrapper {\n");
      out.write("        background: #50a3a2;\n");
      out.write("        background: -webkit-linear-gradient(top left, #50a3a2 0%, #53e3a6 100%);\n");
      out.write("        background: -moz-linear-gradient(top left, #50a3a2 0%, #53e3a6 100%);\n");
      out.write("        background: -o-linear-gradient(top left, #50a3a2 0%, #53e3a6 100%);\n");
      out.write("        background: linear-gradient(to bottom right, #50a3a2 0%, #53e3a6 100%);\n");
      out.write("        position: absolute;\n");
      out.write("        top: 50%;\n");
      out.write("        left: 0;\n");
      out.write("        width: 100%;\n");
      out.write("        height: 400px;\n");
      out.write("        margin-top: -200px;\n");
      out.write("        overflow: hidden;\n");
      out.write("        }\n");
      out.write("        #tab0 .wrapper.form-success .container h1 {\n");
      out.write("        transform: translateY(85px);\n");
      out.write("        }\n");
      out.write("        #tab0 .container {\n");
      out.write("        max-width: 600px;\n");
      out.write("        margin: 0 auto;\n");
      out.write("        padding: 80px 0;\n");
      out.write("        height: 400px;\n");
      out.write("        text-align: center;\n");
      out.write("        }\n");
      out.write("        #tab0 .container h1 {\n");
      out.write("        font-size: 40px;\n");
      out.write("        transition-duration: 1s;\n");
      out.write("        transition-timing-function: ease-in-put;\n");
      out.write("        font-weight: 200;\n");
      out.write("        }\n");
      out.write("        #tab0 form {\n");
      out.write("        padding: 20px 0;\n");
      out.write("        position: relative;\n");
      out.write("        z-index: 2;\n");
      out.write("        }\n");
      out.write("        #tab0 form input {\n");
      out.write("        appearance: none;\n");
      out.write("        outline: 0;\n");
      out.write("        border: 1px solid rgba(255, 255, 255, 0.4);\n");
      out.write("        background-color: rgba(255, 255, 255, 0.2);\n");
      out.write("        width: 250px;\n");
      out.write("        border-radius: 3px;\n");
      out.write("        padding: 10px 15px;\n");
      out.write("        margin: 0 auto 10px auto;\n");
      out.write("        display: block;\n");
      out.write("        text-align: center;\n");
      out.write("        font-size: 18px;\n");
      out.write("        color: white;\n");
      out.write("        transition-duration: 0.25s;\n");
      out.write("        font-weight: 300;\n");
      out.write("        }\n");
      out.write("        #tab0 form input:hover {\n");
      out.write("        background-color: rgba(255, 255, 255, 0.4);\n");
      out.write("        }\n");
      out.write("        #tab0 form input:focus {\n");
      out.write("        background-color: white;\n");
      out.write("        width: 300px;\n");
      out.write("        color: #53e3a6;\n");
      out.write("        }\n");
      out.write("        #tab0 form button {\n");
      out.write("        appearance: none;\n");
      out.write("        outline: 0;\n");
      out.write("        background-color: white;\n");
      out.write("        border: 0;\n");
      out.write("        padding: 10px 15px;\n");
      out.write("        color: #53e3a6;\n");
      out.write("        border-radius: 3px;\n");
      out.write("        width: 250px;\n");
      out.write("        cursor: pointer;\n");
      out.write("        font-size: 18px;\n");
      out.write("        transition-duration: 0.25s;\n");
      out.write("        }\n");
      out.write("        #tab0 form button:hover {\n");
      out.write("        background-color: #f5f7f9;\n");
      out.write("        }\n");
      out.write("        #tab0 .bg-bubbles {\n");
      out.write("        position: absolute;\n");
      out.write("        top: 0;\n");
      out.write("        left: 0;\n");
      out.write("        width: 100%;\n");
      out.write("        height: 100%;\n");
      out.write("        z-index: 1;\n");
      out.write("        }\n");
      out.write("        .bg-bubbles li {\n");
      out.write("        position: absolute;\n");
      out.write("        list-style: none;\n");
      out.write("        display: block;\n");
      out.write("        width: 40px;\n");
      out.write("        height: 40px;\n");
      out.write("        background-color: rgba(255, 255, 255, 0.15);\n");
      out.write("        bottom: -160px;\n");
      out.write("        -webkit-animation: square 25s infinite;\n");
      out.write("        animation: square 25s infinite;\n");
      out.write("        -webkit-transition-timing-function: linear;\n");
      out.write("        transition-timing-function: linear;\n");
      out.write("        }\n");
      out.write("        .bg-bubbles li:nth-child(1) {\n");
      out.write("        left: 10%;\n");
      out.write("        }\n");
      out.write("        .bg-bubbles li:nth-child(2) {\n");
      out.write("        left: 20%;\n");
      out.write("        width: 80px;\n");
      out.write("        height: 80px;\n");
      out.write("        animation-delay: 2s;\n");
      out.write("        animation-duration: 17s;\n");
      out.write("        }\n");
      out.write("        .bg-bubbles li:nth-child(3) {\n");
      out.write("        left: 25%;\n");
      out.write("        animation-delay: 4s;\n");
      out.write("        }\n");
      out.write("        .bg-bubbles li:nth-child(4) {\n");
      out.write("        left: 40%;\n");
      out.write("        width: 60px;\n");
      out.write("        height: 60px;\n");
      out.write("        animation-duration: 22s;\n");
      out.write("        background-color: rgba(255, 255, 255, 0.25);\n");
      out.write("        }\n");
      out.write("        .bg-bubbles li:nth-child(5) {\n");
      out.write("        left: 70%;\n");
      out.write("        }\n");
      out.write("        .bg-bubbles li:nth-child(6) {\n");
      out.write("        left: 80%;\n");
      out.write("        width: 120px;\n");
      out.write("        height: 120px;\n");
      out.write("        animation-delay: 3s;\n");
      out.write("        background-color: rgba(255, 255, 255, 0.2);\n");
      out.write("        }\n");
      out.write("        .bg-bubbles li:nth-child(7) {\n");
      out.write("        left: 32%;\n");
      out.write("        width: 160px;\n");
      out.write("        height: 160px;\n");
      out.write("        animation-delay: 7s;\n");
      out.write("        }\n");
      out.write("        .bg-bubbles li:nth-child(8) {\n");
      out.write("        left: 55%;\n");
      out.write("        width: 20px;\n");
      out.write("        height: 20px;\n");
      out.write("        animation-delay: 15s;\n");
      out.write("        animation-duration: 40s;\n");
      out.write("        }\n");
      out.write("        .bg-bubbles li:nth-child(9) {\n");
      out.write("        left: 25%;\n");
      out.write("        width: 10px;\n");
      out.write("        height: 10px;\n");
      out.write("        animation-delay: 2s;\n");
      out.write("        animation-duration: 40s;\n");
      out.write("        background-color: rgba(255, 255, 255, 0.3);\n");
      out.write("        }\n");
      out.write("        .bg-bubbles li:nth-child(10) {\n");
      out.write("        left: 90%;\n");
      out.write("        width: 160px;\n");
      out.write("        height: 160px;\n");
      out.write("        animation-delay: 11s;\n");
      out.write("        }\n");
      out.write("        @-webkit-keyframes square {\n");
      out.write("        0% {\n");
      out.write("            transform: translateY(0);\n");
      out.write("        }\n");
      out.write("        100% {\n");
      out.write("            transform: translateY(-700px) rotate(600deg);\n");
      out.write("        }\n");
      out.write("        }\n");
      out.write("        @keyframes square {\n");
      out.write("        0% {\n");
      out.write("            transform: translateY(0);\n");
      out.write("        }\n");
      out.write("        100% {\n");
      out.write("            transform: translateY(-700px) rotate(600deg);\n");
      out.write("        }\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        /* tab image, h1 */\n");
      out.write("        .img-base {\n");
      out.write("            background-position: center center;\n");
      out.write("            background-repeat:  no-repeat;\n");
      out.write("            background-attachment: fixed;\n");
      out.write("            background-size:  cover;\n");
      out.write("            background-color: #999;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .h1-base {\n");
      out.write("            /* margin-left: 11vw; */\n");
      out.write("            font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;\n");
      out.write("            font-weight: bold;\n");
      out.write("            font-size: 40px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .font {\n");
      out.write("            position: absolute;\n");
      out.write("            top: 70vh;\n");
      out.write("            left: 50%;\n");
      out.write("            transform: translate(-50%, -50%);\n");
      out.write("            background: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* tab1 */\n");
      out.write("        .tab1-img {\n");
      out.write("            width: 35vw;\n");
      out.write("            height: 60vh;\n");
      out.write("            margin-top: 7vh;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* tab3 */\n");
      out.write("        .tab1-img1 {\n");
      out.write("            width: 35vw;\n");
      out.write("            height: 60vh;\n");
      out.write("            margin-top: 7vh;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* tab2 */\n");
      out.write("        .tab2-img {\n");
      out.write("            width: 35vw;\n");
      out.write("            height: 60vh;\n");
      out.write("            margin-top: 7vh;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* tab3 */\n");
      out.write("        .tab3-img1 {\n");
      out.write("            width: 35vw;\n");
      out.write("            height: 60vh;\n");
      out.write("            margin-top: 7vh;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .tab3-img2 {\n");
      out.write("            width: 35vw;\n");
      out.write("            height: 60vh;\n");
      out.write("            margin-top: 7vh;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* tab4 */\n");
      out.write("        #tab4 { \n");
      out.write("            background-image: url(resources/images/메인.jpg) ;\n");
      out.write("            background-position: center center;\n");
      out.write("            background-repeat:  no-repeat;\n");
      out.write("            background-attachment: fixed;\n");
      out.write("            background-size:  cover;\n");
      out.write("            background-color: #999;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        #tab4{\n");
      out.write("            padding: 0;\n");
      out.write("            font-family: exo, sans-serif;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div id=\"tab0\">\n");
      out.write("        <div class=\"wrapper wra0\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <h1>Welcome</h1>\n");
      out.write("    \n");
      out.write("                <form class=\"form\">\n");
      out.write("                    <input type=\"text\" placeholder=\"Username\">\n");
      out.write("                    <input type=\"password\" placeholder=\"Password\">\n");
      out.write("                    <button type=\"submit\" id=\"login-button\">Login</button>\n");
      out.write("                    <p><a href=\"\" onclick=\"\">다음에 할게요</a></p>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <script>\n");
      out.write("            $(\"#login-button\").click(function (event) {\n");
      out.write("                event.preventDefault();\n");
      out.write("\n");
      out.write("                $('form').fadeOut(500);\n");
      out.write("                $('.wrapper').addClass('form-success');\n");
      out.write("            });\n");
      out.write("        </script>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div id=\"tab1\">\n");
      out.write("        <img src=\"img/3.PNG\" class=\"img-base tab1-img\">\n");
      out.write("        <div class=\"wrapper wra1\">\n");
      out.write("            <div class=\"message msg1\">\n");
      out.write("                <h1>온라인으로 나만의 단어장과 함께 공부할 친구를 찾으세요!</h1>    \n");
      out.write("                <p>저희 '외웟' 홈페이지에서는 자신의 단어장을 만들고, 그로 인해 재밌는 게임으로 공부를 할 수 있으며, 클래스를 꾸려 함께 공부할 수 있게 해놓았습니다.</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div id=\"tab2\">\n");
      out.write("        <img src=\"img/2-2.PNG\" class=\"img-base tab2-img\">\n");
      out.write("        <div class=\"wrapper wra2\">\n");
      out.write("            <div class=\"message\">\n");
      out.write("                <h1>온라인으로 나만의 단어장과 함께 공부할 친구를 찾으세요!</h1>    \n");
      out.write("                <p>저희 '외웟' 홈페이지에서는 자신의 단어장을 만들고, 그로 인해 재밌는 게임으로 공부를 할 수 있으며, 클래스를 꾸려 함께 공부할 수 있게 해놓았습니다.</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div id=\"tab3\">\n");
      out.write("        <img src=\"img/1.PNG\" alt=\"\" class=\"img-base tab3-img1\">\n");
      out.write("        <img src=\"img/2-1.PNG\" class=\"img-base tab3-img2\">\n");
      out.write("        <div class=\"wrapper wra3\">\n");
      out.write("            <div class=\"message\">\n");
      out.write("                <h1>온라인으로 나만의 단어장과 함께 공부할 친구를 찾으세요!</h1>    \n");
      out.write("                <p>저희 '외웟' 홈페이지에서는 자신의 단어장을 만들고, 그로 인해 재밌는 게임으로 공부를 할 수 있으며, 클래스를 꾸려 함께 공부할 수 있게 해놓았습니다.</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div id=\"tab4\">\n");
      out.write("        <!-- <img src=\"img/1대1.jpg\" class=\"img-base\">\n");
      out.write("        <div class=\"font\">\n");
      out.write("        <h1 class=\"h1-base\">온라인으로 단어를 함께 공부해 나가는 선생님을 만나보세요!</h1>\n");
      out.write("        </div>\n");
      out.write("        <p></p> -->\n");
      out.write("\n");
      out.write("        <div class=\"wrapper wra4\">\n");
      out.write("\t        ");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t<button onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ admin1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\">inquire.ad</button>\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t<button onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ admin2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\">memberManage.ad</button>\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t<button onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ class1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\">classify.cl</button>\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t<button onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ class2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\">total.cl</button>\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t<button onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ inquire }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\">inquire.in</button>\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t<button onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ visit1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\">day.vi</button>\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t<button onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ visit2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\">month.vi</button>\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t<button onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ visit3 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\">time.vi</button>\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005furl_005f8(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t<button onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ voca1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\">classify.voca</button>\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005furl_005f9(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t<button onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ voca2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\">total.voca</button>\n");
      out.write("            <div class=\"message\">\n");
      out.write("                <h1>온라인으로 나만의 단어장과 함께 공부할 친구를 찾으세요!</h1>    \n");
      out.write("                <p>저희 '외웟' 홈페이지에서는 자신의 단어장을 만들고, 그로 인해 재밌는 게임으로 공부를 할 수 있으며, 클래스를 꾸려 함께 공부할 수 있게 해놓았습니다.</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/home.jsp(482,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setVar("admin1");
      // /WEB-INF/views/home.jsp(482,9) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("inquire.ad");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/views/home.jsp(484,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setVar("admin2");
      // /WEB-INF/views/home.jsp(484,3) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("memberManage.ad");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/views/home.jsp(486,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setVar("class1");
      // /WEB-INF/views/home.jsp(486,3) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("classify.cl");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /WEB-INF/views/home.jsp(488,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setVar("class2");
      // /WEB-INF/views/home.jsp(488,3) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("total.cl");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /WEB-INF/views/home.jsp(490,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setVar("inquire");
      // /WEB-INF/views/home.jsp(490,3) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("inquire.in");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /WEB-INF/views/home.jsp(492,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setVar("visit1");
      // /WEB-INF/views/home.jsp(492,3) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("day.vi");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /WEB-INF/views/home.jsp(494,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setVar("visit2");
      // /WEB-INF/views/home.jsp(494,3) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("month.vi");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /WEB-INF/views/home.jsp(496,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setVar("visit3");
      // /WEB-INF/views/home.jsp(496,3) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue("time.vi");
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f8_reused = false;
    try {
      _jspx_th_c_005furl_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f8.setParent(null);
      // /WEB-INF/views/home.jsp(498,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f8.setVar("voca1");
      // /WEB-INF/views/home.jsp(498,3) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f8.setValue("classify.voca");
      int _jspx_eval_c_005furl_005f8 = _jspx_th_c_005furl_005f8.doStartTag();
      if (_jspx_th_c_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
      _jspx_th_c_005furl_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f8, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f9 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f9_reused = false;
    try {
      _jspx_th_c_005furl_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f9.setParent(null);
      // /WEB-INF/views/home.jsp(500,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f9.setVar("voca2");
      // /WEB-INF/views/home.jsp(500,3) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f9.setValue("total.voca");
      int _jspx_eval_c_005furl_005f9 = _jspx_th_c_005furl_005f9.doStartTag();
      if (_jspx_th_c_005furl_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f9);
      _jspx_th_c_005furl_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f9, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f9_reused);
    }
    return false;
  }
}
